### PR TITLE
Deps

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Trying to help get the Python 3.10 builds working. Started by tweaking the dependencies:
* Move numpy to more standard config
* Strip out some unneeded from host/run/test
* Re-render

We'll see what fails from there.

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

Am curious to see logs from this.

**Comment by akrherz** [comment]
win python3.7 failure
```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py" 
import: 'wrf'
Traceback (most recent call last):
  File "D:\bld\wrf-python_1642196808128\_test_env\lib\site-packages\wrf\__init__.py", line 6, in <module>
    from . import api
  File "D:\bld\wrf-python_1642196808128\_test_env\lib\site-packages\wrf\api.py", line 1, in <module>
    from .config import (xarray_enabled, disable_xarray, enable_xarray,
  File "D:\bld\wrf-python_1642196808128\_test_env\lib\site-packages\wrf\config.py", line 6, in <module>
    from ._wrffortran import (fomp_enabled, fomp_set_num_threads,
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bld\wrf-python_1642196808128\test_tmp\run_test.py", line 2, in <module>
    import wrf
  File "D:\bld\wrf-python_1642196808128\_test_env\lib\site-packages\wrf\__init__.py", line 18, in <module>
    from . import api
  File "D:\bld\wrf-python_1642196808128\_test_env\lib\site-packages\wrf\api.py", line 1, in <module>
    from .config import (xarray_enabled, disable_xarray, enable_xarray,
  File "D:\bld\wrf-python_1642196808128\_test_env\lib\site-packages\wrf\config.py", line 6, in <module>
    from ._wrffortran import (fomp_enabled, fomp_set_num_threads,
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by akrherz** [comment]
My uneducated guess is that this

```diff
- $PYTHON setup.py install --single-version-externally-managed --record=record.txt
+ $PYTHON -m pip install . -vv
```
has troubles on windows?

**Comment by akrherz** [comment]
My guess above was wrong as per thrashing in #59  :(

cross-referencing interesting discussion NCAR/wrf-python#110 denoting that conda-forge wrf-python may be broken on windows already.

**Comment by akrherz** [comment]
@dopplershift I think this is mostly/completely(?) obsoleted now with #59 in?

**Comment by dopplershift** [comment]
Yeah, I think this can go away.

**Pull request closed without merging**
